#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
yarn lint:fix ||
(
    echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

git add .

echo '🎉🎉🎉🎉 Yeayy, there is no error in your code... I am committing this now. ✨🚀🏄‍♂️🍻'
