name: Testing CI

on:
  push:
    branches: [ main, qa ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - run: yarn
    - run: yarn lint
    - run: yarn test
